vocabulary_urls= [
  "https://storage.googleapis.com/opentargets-vocabularies_2020_09/ANATOMY-MESH.json",
  # "https://storage.googleapis.com/opentargets-vocabularies/ANTROPOLOGY-MESH.json",
  # "https://storage.googleapis.com/opentargets-vocabularies/CHEMICAL-MESH.json",
  "https://storage.googleapis.com/opentargets-vocabularies_2020_09/DIAGNOSTICS-MESH.json",
  # "https://storage.googleapis.com/opentargets-vocabularies/DISCIPLINE-MESH.json",
  # "https://storage.googleapis.com/opentargets-vocabularies/DISEASE-EPMC.json",
  # "https://storage.googleapis.com/opentargets-vocabularies/DISEASE-MESH.json",
  "https://storage.googleapis.com/opentargets-vocabularies_2020_09/DISEASE-OPENTARGETS.json",
  # "https://storage.googleapis.com/opentargets-vocabularies/GENE-EPMC.json",
  "https://storage.googleapis.com/opentargets-vocabularies_2020_09/HEALTHCARE-MESH.json",
  # "https://storage.googleapis.com/opentargets-vocabularies/HUMANITIES-MESH.json",
  # "https://storage.googleapis.com/opentargets-vocabularies/INFORMATIONSCIENCE-MESH.json",
  "https://storage.googleapis.com/opentargets-vocabularies_2020_09/LOC-MESH.json",
  # "https://storage.googleapis.com/opentargets-vocabularies/NAMEDGROUP-MESH.json",
  "https://storage.googleapis.com/opentargets-vocabularies_2020_09/ORGANISM-MESH.json",
  # "https://storage.googleapis.com/opentargets-vocabularies/PATHWAY-OPENTARGETS.json",
  # "https://storage.googleapis.com/opentargets-vocabularies/PHENOTYPE-EPMC.json",
  "https://storage.googleapis.com/opentargets-vocabularies_2020_09/PROCESS-MESH.json",
  # "https://storage.googleapis.com/opentargets-vocabularies/PROTEINCOMPLEX-CHEMBL.json",
  # "https://storage.googleapis.com/opentargets-vocabularies/PROTEINCOMPLEX-COMPLEXPORTAL.json",
  # "https://storage.googleapis.com/opentargets-vocabularies/PROTEINCOMPLEX-CORUM.json",
  # "https://storage.googleapis.com/opentargets-vocabularies/PROTEINCOMPLEX-GO.json",
  # "https://storage.googleapis.com/opentargets-vocabularies/PSICHIATRY-MESH.json",
  # "https://storage.googleapis.com/opentargets-vocabularies/PUBLICATION-MESH.json",
  "https://storage.googleapis.com/opentargets-vocabularies_2020_09/GENE-OPENTARGETS.json",
  # "https://storage.googleapis.com/opentargets-vocabularies/TECHNOLOGY-MESH.json"
  # "https://storage.googleapis.com/opentargets-vocabularies/GENE-LEXEBI.json",
  # "https://storage.googleapis.com/opentargets-vocabularies/DISEASE-LEXEBI.json",
  "https://storage.googleapis.com/opentargets-vocabularies_2020_09/PHENOTYPE-HPO.json",
  "https://storage.googleapis.com/opentargets-vocabularies_2020_09/DRUG-CHEMBL.json"
  # "https://storage.googleapis.com/opentargets-vocabularies/DISEASEALT-MONDO.json"
]
